name: "raccoon: Build and test"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check
      run: cargo check --verbose
    - name: Test
      run: cargo test --verbose
    - name: Clippy
      run: cargo clippy --all-targets --all-features --verbose
    - name: Format
      run: cargo fmt --all -- --check --verbose
